---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-management-frontend
    component: "frontend"
  name: employee-management-frontend-service
  namespace: depauna
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
  selector:
    app: employee-management-frontend
    component: "frontend"
