---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
  name: employee-management-frontend-ingress
  namespace: depauna
spec:
  rules:
    - host: 137.135.173.235
      http:
        paths:
          - backend:
              serviceName: employee-management-frontend-service
              servicePort: 80
            path: /