---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
  name: employee-management-frontend-ingress
  namespace: depauna
spec:
  rules:
    - host: kubernetes-elb-depauna-569195912.eu-west-1.elb.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: employee-management-frontend-service
              servicePort: 4200
            path: /